<Project>

  <ItemGroup>
    <!-- Assets handling: Shader & Texture raw sources -->
    <VulkanShader Include="Assets\Shaders\*.hlsl" />
    <VulkanShaderHeader Include="Assets\Shaders\*.hlsli" />
    <RawTexture Include="Assets\Textures\**\*.png" />

    <!-- Verbatim copy ALL assets by default -->
    <None Update="Assets\**" CopyToOutputDirectory="PreserveNewest" />

    <!-- OVERRIDE raw sources: Keep them visible in VS but do NOT copy verbatim to Output -->
    <None Update="Assets\Shaders\*.hlsl" CopyToOutputDirectory="Never" />
    <None Update="Assets\Shaders\*.hlsli" CopyToOutputDirectory="Never" />
    <None Update="Assets\Textures\**\*.png" CopyToOutputDirectory="Never" />
    
    <Folder Include="Assets\" />
  </ItemGroup>

  <!-- Auto-compile MSBuild steps -->
  <Target Name="CompileVulkanShaders" BeforeTargets="AssignTargetPaths" Inputs="@(VulkanShader);@(VulkanShaderHeader)" Outputs="@(VulkanShader->'$(IntermediateOutputPath)Assets\%(Filename).spv')">
    <Message Text="[Vulkan] Компиляция шейдера: %(VulkanShader.Filename)%(VulkanShader.Extension)" Importance="high" />
    <MakeDir Directories="$(IntermediateOutputPath)Assets" />
    <Exec Command="dotnet run --project ../MinecraftPT.ShaderCompiler/MinecraftPT.ShaderCompiler.csproj -- &quot;%(VulkanShader.FullPath)&quot; &quot;$(MSBuildProjectDirectory)\$(IntermediateOutputPath)Assets\%(VulkanShader.Filename).spv&quot; -I &quot;%(VulkanShader.RootDir)%(VulkanShader.Directory).&quot;" />
    <ItemGroup>
      <EmbeddedResource Include="$(IntermediateOutputPath)Assets\%(VulkanShader.Filename).spv">
        <Link>Assets\Shaders\%(VulkanShader.Filename).spv</Link>
      </EmbeddedResource>
    </ItemGroup>
  </Target>

  <Target Name="CompileTextures" BeforeTargets="AssignTargetPaths" Inputs="@(RawTexture)" Outputs="@(RawTexture->'$(IntermediateOutputPath)%(RelativeDir)%(Filename).ztex')">
    <Message Text="[Текстуры] Компиляция: %(RawTexture.Filename)%(RawTexture.Extension)" Importance="high" />
    <MakeDir Directories="$(IntermediateOutputPath)%(RawTexture.RelativeDir)" />
    <Exec Command="dotnet run --project ../MinecraftPT.TextureCompiler/MinecraftPT.TextureCompiler.csproj --configuration Release -- &quot;%(RawTexture.Identity)&quot; &quot;$(IntermediateOutputPath)%(RawTexture.RelativeDir)%(RawTexture.Filename).ztex&quot;" />
    <ItemGroup>
      <EmbeddedResource Include="$(IntermediateOutputPath)%(RawTexture.RelativeDir)%(RawTexture.Filename).ztex">
        <Link>%(RawTexture.RelativeDir)%(RawTexture.Filename).ztex</Link>
      </EmbeddedResource>
    </ItemGroup>
  </Target>

</Project>
